#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

/* generated by data-raw/make_callentries.R */
extern SEXP carrow_c_array_from_sexp(SEXP buffers_sexp, SEXP length_sexp, SEXP null_count_sexp, SEXP int64_sexp, SEXP children_sexp, SEXP dictionary_xptr);
extern SEXP carrow_c_array_info(SEXP array_data_xptr);
extern SEXP carrow_c_carrow_array_stream(SEXP array_list, SEXP schema_xptr);
extern SEXP carrow_c_function_array_stream(SEXP schema_xptr, SEXP call, SEXP env);
extern SEXP carrow_c_exportable_array_stream(SEXP parent_array_stream_xptr);
extern SEXP carrow_c_carrow_array_stream_get_schema(SEXP array_stream_xptr);
extern SEXP carrow_c_carrow_array_stream_get_next(SEXP array_stream_xptr);
extern SEXP carrow_c_array_validate(SEXP array_sexp);
extern SEXP carrow_c_logical_from_bitmask(SEXP bitmask, SEXP start_sexp, SEXP end_sexp);
extern SEXP carrow_c_bitmask_from_logical(SEXP lgl_sexp);
extern SEXP carrow_c_logical_from_array(SEXP array_sexp);
extern SEXP carrow_c_integer_from_array(SEXP array_sexp);
extern SEXP carrow_c_double_from_array(SEXP array_sexp);
extern SEXP carrow_c_raw_from_array(SEXP array_sexp);
extern SEXP carrow_c_character_from_array(SEXP array_sexp);
extern SEXP carrow_c_buffers_from_character(SEXP chr);
extern SEXP carrow_c_deep_copy(SEXP array_sexp);
extern SEXP carrow_c_double_from_int64(SEXP value, SEXP start_sexp, SEXP end_sexp);
extern SEXP carrow_c_int64_from_double(SEXP dbl_sexp);
extern SEXP carrow_c_int64_from_integer(SEXP int_sexp);
extern SEXP carrow_c_exportable_schema(SEXP schema_xptr);
extern SEXP carrow_c_exportable_array(SEXP array_data_xptr);
extern SEXP carrow_c_pointer(SEXP obj_sexp);
extern SEXP carrow_c_pointer_addr_dbl(SEXP ptr);
extern SEXP carrow_c_pointer_addr_chr(SEXP ptr);
extern SEXP carrow_c_pointer_move(SEXP ptr);
extern SEXP carrow_c_schema_blank();
extern SEXP carrow_c_array_blank();
extern SEXP carrow_c_array_stream_blank();
extern SEXP carrow_c_schema_xptr_new(SEXP format_sexp, SEXP name_sexp, SEXP metadata_sexp, SEXP flags_sexp, SEXP children_sexp, SEXP dictionary_xptr);
extern SEXP carrow_c_schema_deep_copy(SEXP schema_xptr);
extern SEXP carrow_c_schema_data(SEXP schema_xptr);
extern SEXP carrow_c_xptr_addr(SEXP xptr);

static const R_CallMethodDef CallEntries[] = {
    {"carrow_c_array_from_sexp", (DL_FUNC) &carrow_c_array_from_sexp, 6},
  {"carrow_c_array_info", (DL_FUNC) &carrow_c_array_info, 1},
  {"carrow_c_carrow_array_stream", (DL_FUNC) &carrow_c_carrow_array_stream, 2},
  {"carrow_c_function_array_stream", (DL_FUNC) &carrow_c_function_array_stream, 3},
  {"carrow_c_exportable_array_stream", (DL_FUNC) &carrow_c_exportable_array_stream, 1},
  {"carrow_c_carrow_array_stream_get_schema", (DL_FUNC) &carrow_c_carrow_array_stream_get_schema, 1},
  {"carrow_c_carrow_array_stream_get_next", (DL_FUNC) &carrow_c_carrow_array_stream_get_next, 1},
  {"carrow_c_array_validate", (DL_FUNC) &carrow_c_array_validate, 1},
  {"carrow_c_logical_from_bitmask", (DL_FUNC) &carrow_c_logical_from_bitmask, 3},
  {"carrow_c_bitmask_from_logical", (DL_FUNC) &carrow_c_bitmask_from_logical, 1},
  {"carrow_c_logical_from_array", (DL_FUNC) &carrow_c_logical_from_array, 1},
  {"carrow_c_integer_from_array", (DL_FUNC) &carrow_c_integer_from_array, 1},
  {"carrow_c_double_from_array", (DL_FUNC) &carrow_c_double_from_array, 1},
  {"carrow_c_raw_from_array", (DL_FUNC) &carrow_c_raw_from_array, 1},
  {"carrow_c_character_from_array", (DL_FUNC) &carrow_c_character_from_array, 1},
  {"carrow_c_buffers_from_character", (DL_FUNC) &carrow_c_buffers_from_character, 1},
  {"carrow_c_deep_copy", (DL_FUNC) &carrow_c_deep_copy, 1},
  {"carrow_c_double_from_int64", (DL_FUNC) &carrow_c_double_from_int64, 3},
  {"carrow_c_int64_from_double", (DL_FUNC) &carrow_c_int64_from_double, 1},
  {"carrow_c_int64_from_integer", (DL_FUNC) &carrow_c_int64_from_integer, 1},
  {"carrow_c_exportable_schema", (DL_FUNC) &carrow_c_exportable_schema, 1},
  {"carrow_c_exportable_array", (DL_FUNC) &carrow_c_exportable_array, 1},
  {"carrow_c_pointer", (DL_FUNC) &carrow_c_pointer, 1},
  {"carrow_c_pointer_addr_dbl", (DL_FUNC) &carrow_c_pointer_addr_dbl, 1},
  {"carrow_c_pointer_addr_chr", (DL_FUNC) &carrow_c_pointer_addr_chr, 1},
  {"carrow_c_pointer_move", (DL_FUNC) &carrow_c_pointer_move, 1},
  {"carrow_c_schema_blank", (DL_FUNC) &carrow_c_schema_blank, 0},
  {"carrow_c_array_blank", (DL_FUNC) &carrow_c_array_blank, 0},
  {"carrow_c_array_stream_blank", (DL_FUNC) &carrow_c_array_stream_blank, 0},
  {"carrow_c_schema_xptr_new", (DL_FUNC) &carrow_c_schema_xptr_new, 6},
  {"carrow_c_schema_deep_copy", (DL_FUNC) &carrow_c_schema_deep_copy, 1},
  {"carrow_c_schema_data", (DL_FUNC) &carrow_c_schema_data, 1},
  {"carrow_c_xptr_addr", (DL_FUNC) &carrow_c_xptr_addr, 1},
  {NULL, NULL, 0}
};
/* end generated by data-raw/make_callentries.R */

void R_init_carrow(DllInfo *dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
